### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by The-Hasanov** [NicklasWallgren/PokemonGoAPI-PHP#14]
`php examples\RetrievePlayerStatsExample.php`
```
Fatal error: Uncaught exception 'Exception' with message 'Incorrect wire format for field 1, expected: 0 got: 2' in E:\OpenServer\domains\goapi\res\POGOProtos\Networking\Envelopes\ResponseEnvelope.php:153
```
```
Stack trace:
#0 E:\OpenServer\domains\goapi\src\Handlers\RequestHandler.php(181): POGOProtos\Networking\Envelopes\ResponseEnvelope->read('\n<html><head>\n<...')
#1 E:\OpenServer\domains\goapi\src\Handlers\RequestHandler.php(166): NicklasW\PkmGoApi\Handlers\RequestHandler->unmarshall(Object(GuzzleHttp\Psr7\Response))
#2 E:\OpenServer\domains\goapi\src\Handlers\RequestHandler.php(86): NicklasW\PkmGoApi\Handlers\RequestHandler->call(Object(POGOProtos\Networking\Envelopes\RequestEnvelope))
#3 E:\OpenServer\domains\goapi\src\Services\Request\InventoryRequestService.php(19): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetInventoryRequest))
#4 E:\OpenServer\domains\goapi\src\Api\Player\Inventory.php(37): NicklasW\PkmGoApi\Services\Request\InventoryRequestService->getInventory()
#5 E:\Open in E:\OpenServer\domains\goapi\res\POGOProtos\Networking\Envelopes\ResponseEnvelope.php on line 153
```

**Comment by NicklasWallgren** [comment]
Thanks for the report. I'll investigate further.

**Comment by NicklasWallgren** [comment]
Try to run the example again, this only happens 1 / 100 request. The pokemon go backend has changed somewhat.

**Comment by The-Hasanov** [comment]
all time i take error 
i think it's my location problem but i try other bots and api work correctly

**Comment by NicklasWallgren** [comment]
Found the issue, I didn't correctly handle 500 errors from the server. The pokemon go servers must be overloaded at your location.

Try the latest release, it should prompt the correct error message.

**Comment by The-Hasanov** [comment]
502 :)
