### ISSUE TITLE
protocolbuffers.inc.php error

### ISSUE THREAD

**Issue by Gandaflux** [NicklasWallgren/PokemonGoAPI-PHP#69]
Something stop work, or i did smth wrong? yesterday was working ok. 

```
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'skip((1) 64-bit): Error seeking' in PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php:844
Stack trace:
#0 PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/POGOProtos/Data/PlayerData.php(163): Protobuf::skip_field(Resource id #58, 0)
#1 PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php(84): POGOProtos\Data\PlayerData-&gt;read(Resource id #58, 6)
#2 PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/POGOProtos/Data/PlayerData.php(31): ProtobufMessage-&gt;__construct(Resource id #58, 6)
#3 PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/POGOProtos/Networking/Responses/GetPlayerResponse.php(49): POGOProtos\Data\PlayerData-&gt;__construct(Resource id #58, 6)
#4 PokemonGoAPI-PHP/src/Requests/GetPlayerRequest.php(54): POGOProtos\Networking\Responses\GetPlayerResponse-&gt;read('\x08\x01\x12Y\x08\ in <b>PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/protocolbuffers.inc.php</b> on line <b>844</b><br />
```

**Comment by lambasoft** [comment]
Same thing happened to me.
I guess it's because of Niantic banning most of cloud ISPs.
If you run this locally it should work, right ?

**Comment by Gandaflux** [comment]
Nope. After some digging it looks like PlayerResponse packet got additional field.

**Comment by lambasoft** [comment]
Any idea how to fix this ?

**Comment by Gandaflux** [comment]
PokemonGoAPI-PHP/vendor/nicklasw/pogoprotos-php/src/POGOProtos/Data/PlayerData.php

after case 14 add another one:

```
          case 15:
            if($wire !== 0) {
              throw new \Exception("Incorrect wire format for field $field, expected: 0 got: $wire");
            }
            $tmp = Protobuf::read_signed_varint($fp, $limit);
            if ($tmp === false) throw new \Exception('Protobuf::read_varint returned false');
            if ($tmp < Protobuf::MIN_INT32 || $tmp > Protobuf::MAX_INT32) throw new \Exception('int32 out of range');
              // echo $tmp;
            break;
```

**Comment by lambasoft** [comment]
@Gandaflux You're awesome. Thanks for the quick reply. It worked :)

**Comment by NicklasWallgren** [comment]
I have updated the pogoprotos-php repo. Thanks for the help @Gandaflux
