### ISSUE TITLE
Google Authentication Failing

### ISSUE THREAD

**Issue by curt2008** [NicklasWallgren/PokemonGoAPI-PHP#8]
`Fatal error: Call to a member function getAttribute() on null in /home/user123/public_html/files/PokemonGoAPI-PHP/src/Authenticators/GoogleOauth/Parsers/AuthenticationConfirmationInformationParser.php on line 56`

When attempting to use your example

**Comment by NicklasWallgren** [comment]
I will redo the Google Authenticator in the next release.

**Comment by NicklasWallgren** [comment]
The GoogleAuthenticator has been re-implemented. Try it out :)

**Comment by The-Hasanov** [comment]
```
Fatal error: Uncaught exception 'NicklasW\PkmGoApi\Authenticators\Exceptions\ResponseException' with message 'Retrieved a invalid response from the server. Please try again later' in C:\OpenServer\domains\goapi\src\Authenticators\GoogleOauth\Parsers\Parser.php:56
Stack trace:
#0 C:\OpenServer\domains\goapi\src\Authenticators\GoogleOauth\Parsers\TokenParser.php(29): NicklasW\PkmGoApi\Authenticators\GoogleOauth\Parsers\Parser->validateResponse(Object(GuzzleHttp\Psr7\Response))
#1 C:\OpenServer\domains\goapi\src\Authenticators\GoogleOauth\Clients\AuthenticationClient.php(77): NicklasW\PkmGoApi\Authenticators\GoogleOauth\Parsers\TokenParser->parse(Object(GuzzleHttp\Psr7\Response))
#2 C:\OpenServer\domains\goapi\src\Authenticators\GoogleAuthenticator.php(53): NicklasW\PkmGoApi\Authenticators\GoogleOauth\Clients\AuthenticationClient->token(false, false)
#3 C:\OpenServer\domains\goapi\src\Authenticators\GoogleAuthenticator.php(26): NicklasW\PkmGoApi\Authenticators\GoogleAuthenticator->getToken(false, false)
#4 C:\OpenServer\doma in C:\OpenServer\domains\goapi\src\Authenticators\GoogleOauth\Parsers\Parser.php on line 56
```

**Comment by NicklasWallgren** [comment]
@The-Hasanov: Are you using the correct user credentials?

I have tighten up the exception response. Try the latest release.

**Comment by The-Hasanov** [comment]
response 
access your account, you must sign in on the web. Touch Next to start browser sign-in.
i use sms verification

**Comment by NicklasWallgren** [comment]
Ah, we don't support 2-step authentication at this moment. Sorry.

**Comment by curt2008** [comment]
Works perfect, thankyou
